---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: check sonar-scanner installed
      ansible.builtin.command: "sonar-scanner --version"
      changed_when: no
